server:
  port: 9003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  rabbitmq:
    host: 47.94.155.74
    port: 5672
    username: root
    password: Qinfo20180507    
  redis:
    database: 0
    host: 47.94.155.74
    port: 6379
    password: Qinfo20180507
    jedis:
      pool:
        max-active: 10
        max-wait: 10
        max-idle: 2
        min-idle: 2
    timeout: 1000      
      
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml  
  

timeout: 1000  
  
order:
  timeout: 1
